### ISSUE TITLE
ByteBuffer.allocate java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by Vex186** [BryanGIG/PADumper#1]
![Screenshot_20220108-200111_PADumper](https://user-images.githubusercontent.com/72016480/148652961-18354eda-dcb6-4f66-b05e-d1fab921ec97.jpg)

What should i do

**Comment by BryanGIG** [comment]
Hi, can you test this build and inform me?
[app-test-1.0.1.zip](https://github.com/BryanGIG/PADumper/files/7838342/app-test-1.0.1.zip)

**Comment by Vex186** [comment]
> Merhaba, bu yapıyı test edip beni bilgilendirebilir misiniz? [app-test-1.0.1.zip](https://github.com/BryanGIG/PADumper/files/7838342/app-test-1.0.1.zip)

![Screenshot_20220116-143414_PADumper](https://user-images.githubusercontent.com/72016480/149658174-7312d3ab-226f-4caf-bf40-3447a6186e08.jpg)

**Comment by BryanGIG** [comment]
![Screenshot_20220117-045309_PADumper](https://user-images.githubusercontent.com/91574316/149679600-e2542fe2-bfca-4d73-81d8-6bbd7a803c5c.png)
Fixed!
