### ISSUE TITLE
Is work normaly ?

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#11]
![Screenshot_2022-04-28-11-58-03-093_com dumper android](https://user-images.githubusercontent.com/102419809/165667836-3354f1b9-b208-4b3a-b618-081b5de17b9e.jpg)

**Comment by QPLAYid** [comment]
![Screenshot_2022-04-28-11-58-03-093_com dumper android](https://user-images.githubusercontent.com/102419809/165667941-6d18e73b-14cd-4dc6-aadc-d8300e3fb126.jpg)

**Comment by BryanGIG** [comment]
The games seems like make the ELF header invalid so it can't be repaired normally.

**Comment by QPLAYid** [comment]
Have solution ?

**Comment by BryanGIG** [comment]
I'm currently had no solution for this, maybe you can try find the `libil2cpp.so` manually by looking at the maps file
