### ISSUE TITLE
Unable to find base address

### ISSUE THREAD

**Issue by AndnixSH** [BryanGIG/PADumper#13]
It seems PADumper is not able to find lib even game is unprotected like Subway surfers

![image](https://user-images.githubusercontent.com/40742924/172799882-9dd7215e-81f2-40da-b309-c4b31765b4ab.png)

Maps:
[com.kiloo.subwaysurf-maps.txt](https://github.com/BryanGIG/PADumper/files/8868409/com.kiloo.subwaysurf-maps.txt)

**Comment by BryanGIG** [comment]
Its weird that the base address of libil2cpp.so is in `r--p` permission,
libil2cpp.so should be in permission `r-xp` permission as @Perfare said in his [issue](https://github.com/Perfare/Il2CppDumper/issues/530#issuecomment-986035863) .

![image](https://user-images.githubusercontent.com/91574316/172955185-94e8f8b9-6b56-46a4-90c5-5d5d61e8f644.png)

**Comment by BryanGIG** [comment]
![Screenshot_2022-06-10-05-33-11-552_com dumper android](https://user-images.githubusercontent.com/91574316/172956280-38a27d8d-809d-4f9e-928d-07d91d46eafa.jpg)
Im testing `com.dts.freefireth` and it seems like i doesn't having any problem when dumping libil2cpp.so.
The global-metadata.dat is encrypted so you have to find it manually.

**Comment by BryanGIG** [comment]
> Its weird that the base address of libil2cpp.so is in `r--p` permission, libil2cpp.so should be in permission `r-xp` permission as @Perfare said in his [issue](https://github.com/Perfare/Il2CppDumper/issues/530#issuecomment-986035863) .
> 
> ![image](https://user-images.githubusercontent.com/91574316/172955185-94e8f8b9-6b56-46a4-90c5-5d5d61e8f644.png)

i guess im gonna adding option menu about this base address permission.
Thanks for reporting the issue.

**Comment by AndnixSH** [comment]
That's strange, I use emulator running android 7.1.2 for it
GG can dump it without any issues
