### ISSUE TITLE
Dump lib result not valid elf header

### ISSUE THREAD

**Issue by AKNoryx28** [BryanGIG/PADumper#15]
looks like you can see it [here](https://github.com/BryanGIG/PADumper/blob/46c87bb81077946c3cde69a90908b7be42fb81fc/app/src/main/java/com/dumper/android/dumper/Dumper.kt#L170C17-L170C42) sometimes both r--p and r-xp could have a valid elf header.

I think it's better to check if the map start address is an elf header, like this KittyMemory [implementation](https://github.com/MJx0/KittyMemory/blob/ac2f6cde44035d71f2489dd9724243e43127ee64/Android/KittyMemory/KittyMemory.cpp#L305) in c++.
(i actually want to contribute but i know nothing about kotlin 🙃)

Thanks..

**Comment by BryanGIG** [comment]
Thank you for making this issue, this was really helpful.
I had this issue since I start working on this project and didn't really find any useful fix to this issue.
Luckily you found it, really appreciate it 👍🏻
