### ISSUE TITLE
Non Root with Virtual Space Support

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#2]
Saya make virtual space  blacbox32 
[Blacbox virtual app](https://github.com/FBlackBox/BlackBox/releases) 

Saya uds ijinin root penyimpanan tapi saat saya menambah padumper ke dalam virtualnya dan saya mendump apk jadi crash bisa kha 
Kamu memperbaikinya ?
Atau membuatnya sumpport virtual apps ?

**Comment by BryanGIG** [comment]
could you provide some logs? i can't run this BlackBox thing since it doesn't support A13

**Comment by QPLAYid** [comment]
> could you provide some logs? i can't run this BlackBox thing since it doesn't support A13

How to get log ? 
After i get log i send for you

**Comment by BryanGIG** [comment]
Sorry, the project is not supported for non root user at this moment. 
I will consider to add support for non root user through virtual space _(if possible)_

**Comment by BryanGIG** [comment]
Thank you for creating this issue, the non root support is added.
You may try the [latest release](https://github.com/BryanGIG/PADumper/releases)

**Comment by QPLAYid** [comment]
> Thank you for creating this issue, the non root support is added. You may try the [latest release](https://github.com/BryanGIG/PADumper/releases)

Okay
