### ISSUE TITLE
[BUG] SoFixer Failed To Run In Virtual Space Due To Incorrect Path

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#4]
[Video](https://streamable.com/4jh9ql) 

I use no root from blacbox64 
I padumper not detected proses app 
I send vifeo record look that

**Comment by BryanGIG** [comment]
Try use [this](https://github.com/ArcyMods/BlackBox/releases/download/1.8.0/BlackBox-GameGuardian.apk) for of blackbox version
It support until Android 13 and GameGuardian

**Comment by QPLAYid** [comment]
> Try use [this](https://github.com/ArcyMods/BlackBox/releases/download/1.8.0/BlackBox-GameGuardian.apk) for of blackbox version It support until Android 13 and GameGuardian

Btw my device redmi note 10 pro
Android 12 memeui 13

**Comment by QPLAYid** [comment]
![Screenshot_2023-03-03-07-05-23-659_top niunaijun blackbox](https://user-images.githubusercontent.com/102419809/222569383-38d6ba2b-5a76-4f6f-b786-74a122025b79.jpg)
![Screenshot_2023-03-03-07-05-28-187_top niunaijun blackbox](https://user-images.githubusercontent.com/102419809/222569398-52c4573c-c16a-416a-a1b6-704e60e78e0c.jpg)

**Comment by QPLAYid** [comment]
> Try use [this](https://github.com/ArcyMods/BlackBox/releases/download/1.8.0/BlackBox-GameGuardian.apk) for of blackbox version It support until Android 13 and GameGuardian

Emty file not have folder download padumper

**Comment by QPLAYid** [comment]
Done folder dump 
Storage/Download/PADumper/"package apps"

**Comment by BryanGIG** [comment]
is the ELFixer working?

**Comment by QPLAYid** [comment]
> is the ELFixer working?

Not

**Comment by BryanGIG** [comment]
Fixed, you can download [latest release](https://github.com/BryanGIG/PADumper/releases)

**Comment by QPLAYid** [comment]
> Fixed, you can download [latest release](https://github.com/BryanGIG/PADumper/releases)

Okay
