### ISSUE TITLE
Error fix header 

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#5]
Issue fix header. Not working 

![Screenshot_2023-03-22-08-42-21-493_bin mt plus](https://user-images.githubusercontent.com/102419809/226766078-4a528edf-5211-4d08-bbe4-a2fa2e6c6e49.jpg)

**Comment by BryanGIG** [comment]
what game is it?

**Comment by QPLAYid** [comment]
> what game is it?

Evil hunter tycoon

**Comment by QPLAYid** [comment]
Btw bisa di fix ?

**Comment by BryanGIG** [comment]
It's not PADumper bug, its protection from the game.
you might wanted to fix it by analyzing the binary and try fix the header manually
