### ISSUE TITLE
app crash in 2.0.0 version

### ISSUE THREAD

**Issue by Maxdsdsdsd** [BryanGIG/PADumper#6]
![IMG_20220215_174247](https://user-images.githubusercontent.com/33353036/154084980-966d1417-b594-4627-bd99-8e16e09632bd.jpg)
![IMG_20220215_174258](https://user-images.githubusercontent.com/33353036/154084986-a9f90385-5b50-4f23-85ff-589c781bb6d5.jpg)

im give root permissions to app, but its crashes with this log

in version 1.0.1 works normally 

(sorry for my english)

**Comment by BryanGIG** [comment]
What is android version of your device?
