### ISSUE TITLE
[ERROR] Unable to find base address of file

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#6]
![Screenshot_2023-04-03-19-46-44-546_com dumper android](https://user-images.githubusercontent.com/102419809/229488228-7e7fc326-a60e-48e7-a493-3a381c138a0b.jpg)

**Comment by BryanGIG** [comment]
as the error says, the game had no file named ``libil2cpp.so`` or ``global-metadata.dat`` you might wanted to verify if it's an Unity game or not, if it's an Unity game then maybe the file is named by another name, such as `base.apk` or something (this could happend if the game had an split apk for different architecture)

**Comment by QPLAYid** [comment]
> as the error says, the game had no file named `libil2cpp.so` or `global-metadata.dat` you might wanted to verify if it's an Unity game or not, if it's an Unity game then maybe the file is named by another name, such as `base.apk` or something (this could happend if the game had an split apk for different architecture)
Ini game unity saya telah memisahkan il2cpp dari anti split dan game mrmpunyai metadata

**Comment by QPLAYid** [comment]
Game have metada and file il2cpp
I caut and paste il2cpp on split to lib game but paddumper error so i must manualy take metada and il2cpp
