### ISSUE TITLE
Cant dump

### ISSUE THREAD

**Issue by QPLAYid** [BryanGIG/PADumper#9]
![Screenshot_2022-04-26-06-56-45-420_com dumper android](https://user-images.githubusercontent.com/102419809/165181774-c18c9d4e-1a2d-45d2-8f3c-ed1b9129d3df.jpg)

**Comment by BryanGIG** [comment]
You must start your game before dump it

**Comment by QPLAYid** [comment]
Udah padahal saya jalanin game baru saya dump
Apa gara" gamenya protect ya ?

**Comment by BryanGIG** [comment]
The issue fixed in new [release](https://github.com/BryanGIG/PADumper/releases)
